console.log(window);
console.log(console);
console.log(this);
console.log(document);
console.log(document.head);
console.log(document.body);
console.log(window.screen.availWidth);
console.log(window.screen.availHeight);
console.log(window.location);
document.title="Dom"
window.document 
document.write("Suraj")